"""Initial migration

Revision ID: 4b9df3e8dfc4
Revises: 04726bb5e9e8
Create Date: 2024-11-04 22:56:06.342999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9df3e8dfc4'
down_revision: Union[str, None] = '04726bb5e9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
